name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure image name
        id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Get version
        id: tag-version
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        id: build-and-push
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ steps.tag-version.outputs.tag }}
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.RELEASE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
