name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure image name
        id: image-name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get version
        id: tag-version
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GB_TOKEN }}

      - name: Build image
        if: github.event_name != 'pull_request'
        run: |
          docker build -t ${{ steps.image-name.outputs.lowercase }}:${{ steps.tag-version.outputs.tag }} .

      - name: Push to ghcr.io
        if: github.event_name != 'pull_request'
        run: |
          docker push ${{ steps.image-name.outputs.lowercase }}:${{ steps.tag-version.outputs.tag }}
