name: Publish binaries on Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@master
        env:
          CGO_ENABLED: 0
        with:
          github_token: ${{ secrets.GB_TOKEN }}
          goos: linux
          goarch: amd64
