name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: wangyoucao577/go-release-action@master
        env:
          CGO_ENABLED: 0
        with:
          github_token: ${{ secrets.GB_TOKEN }}
          goos: linux
          goarch: amd64
